# Generated by Django 5.2.7 on 2026-02-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0001_initial'),
    ]

    operations = [
    ]
