# Generated by Django 5.2.7 on 2025-11-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Période comptable', 'verbose_name_plural': 'Périodes comptables'},
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Journal activité', 'verbose_name_plural': 'Journal activités'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'address_line1'], 'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-manufacturing_date'], 'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_date'], 'verbose_name': 'Campagne marketing', 'verbose_name_plural': 'Campagnes marketing'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['num_card'], 'verbose_name': 'Carte', 'verbose_name_plural': 'Cartes'},
        ),
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'ordering': ['-date_transaction'], 'verbose_name': 'Transaction de carte', 'verbose_name_plural': 'Transactions de cartes'},
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['name'], 'verbose_name': 'Caisse', 'verbose_name_plural': 'Caisses'},
        ),
        migrations.AlterModelOptions(
            name='cashregistersession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Session de caisse', 'verbose_name_plural': 'Sessions de caisse'},
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'ordering': ['-transaction_time'], 'verbose_name': 'Transaction caisse', 'verbose_name_plural': 'Transactions caisse'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Devise', 'verbose_name_plural': 'Devises'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__username'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['name'], 'verbose_name': 'Tableau de bord', 'verbose_name_plural': 'Tableaux de bord'},
        ),
        migrations.AlterModelOptions(
            name='databackup',
            options={'ordering': ['-backup_date'], 'verbose_name': 'Sauvegarde données', 'verbose_name_plural': 'Sauvegardes données'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-estimated_time'], 'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='deliveryroute',
            options={'ordering': ['name'], 'verbose_name': 'Itinéraire de livraison', 'verbose_name_plural': 'Itinéraires de livraison'},
        ),
        migrations.AlterModelOptions(
            name='deliveryschedule',
            options={'ordering': ['-scheduled_time'], 'verbose_name': 'Planification livraison', 'verbose_name_plural': 'Planifications livraison'},
        ),
        migrations.AlterModelOptions(
            name='deliveryvehicle',
            options={'ordering': ['plate_number'], 'verbose_name': 'Véhicule de livraison', 'verbose_name_plural': 'Véhicules de livraison'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Rayon', 'verbose_name_plural': 'Rayons'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__username'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={'ordering': ['name'], 'verbose_name': 'Rôle employé', 'verbose_name_plural': 'Rôles employés'},
        ),
        migrations.AlterModelOptions(
            name='errorreport',
            options={'ordering': ['-created_at'], 'verbose_name': "Rapport d'erreur", 'verbose_name_plural': "Rapports d'erreur"},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie de dépense', 'verbose_name_plural': 'Catégories de dépenses'},
        ),
        migrations.AlterModelOptions(
            name='financialreport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Rapport financier', 'verbose_name_plural': 'Rapports financiers'},
        ),
        migrations.AlterModelOptions(
            name='generalledger',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Écriture comptable', 'verbose_name_plural': 'Écritures comptables'},
        ),
        migrations.AlterModelOptions(
            name='inventorycountitem',
            options={'ordering': ['inventory_count', 'product__name'], 'verbose_name': 'Ligne inventaire physique', 'verbose_name_plural': 'Lignes inventaires physiques'},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['name'], 'verbose_name': 'Indicateur de performance', 'verbose_name_plural': 'Indicateurs de performance'},
        ),
        migrations.AlterModelOptions(
            name='kpimeasurement',
            options={'ordering': ['-period_start'], 'verbose_name': 'Mesure KPI', 'verbose_name_plural': 'Mesures KPI'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'ordering': ['name'], 'verbose_name': 'Programme de fidélité', 'verbose_name_plural': 'Programmes de fidélité'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyreward',
            options={'ordering': ['points_required'], 'verbose_name': 'Récompense fidélité', 'verbose_name_plural': 'Récompenses fidélité'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Tâche de maintenance', 'verbose_name_plural': 'Tâches de maintenance'},
        ),
        migrations.AlterModelOptions(
            name='mobilemoney',
            options={'ordering': ['-date'], 'verbose_name': 'Mobile Money', 'verbose_name_plural': 'Mobile Moneys'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['user__username'], 'verbose_name': 'Propriétaire', 'verbose_name_plural': 'Propriétaires'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Méthode de paiement', 'verbose_name_plural': 'Méthodes de paiement'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['name'], 'verbose_name': 'Marque', 'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='productreturn',
            options={'ordering': ['-return_date'], 'verbose_name': 'Retour produit', 'verbose_name_plural': 'Retours produits'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product__name', 'name'], 'verbose_name': 'Variante', 'verbose_name_plural': 'Variantes'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-refund_date'], 'verbose_name': 'Remboursement', 'verbose_name_plural': 'Remboursements'},
        ),
        migrations.AlterModelOptions(
            name='reorderrule',
            options={'ordering': ['product__name'], 'verbose_name': 'Règle de réapprovisionnement', 'verbose_name_plural': 'Règles de réapprovisionnement'},
        ),
        migrations.AlterModelOptions(
            name='retailsupply',
            options={'ordering': ['supply', 'name_product'], 'verbose_name': 'Détail approvisionnement', 'verbose_name_plural': 'Détails approvisionnements'},
        ),
        migrations.AlterModelOptions(
            name='returnedproduct',
            options={'ordering': ['-return_date'], 'verbose_name': 'Produit retourné', 'verbose_name_plural': 'Produits retournés'},
        ),
        migrations.AlterModelOptions(
            name='returnitem',
            options={'ordering': ['product_return', 'sale_item__product__name'], 'verbose_name': 'Ligne retour', 'verbose_name_plural': 'Lignes retours'},
        ),
        migrations.AlterModelOptions(
            name='returnreason',
            options={'ordering': ['name'], 'verbose_name': 'Raison de retour', 'verbose_name_plural': 'Raisons de retour'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['sale', 'product__name'], 'verbose_name': 'Ligne vente', 'verbose_name_plural': 'Lignes vente'},
        ),
        migrations.AlterModelOptions(
            name='salepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Paiement vente', 'verbose_name_plural': 'Paiements ventes'},
        ),
        migrations.AlterModelOptions(
            name='salestatus',
            options={'ordering': ['name'], 'verbose_name': 'Statut vente', 'verbose_name_plural': 'Statuts vente'},
        ),
        migrations.AlterModelOptions(
            name='securityincident',
            options={'ordering': ['-id'], 'verbose_name': 'Incident de sécurité', 'verbose_name_plural': 'Incidents de sécurité'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-login_time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='shareholder',
            options={'ordering': ['user__username'], 'verbose_name': 'Actionnaire', 'verbose_name_plural': 'Actionnaires'},
        ),
        migrations.AlterModelOptions(
            name='sousservice',
            options={'ordering': ['-start_service'], 'verbose_name': 'Sous-service', 'verbose_name_plural': 'Sous-services'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product__name'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='stockmovementitem',
            options={'ordering': ['movement', 'product__name'], 'verbose_name': 'Ligne mouvement stock', 'verbose_name_plural': 'Lignes mouvements stock'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='storenetwork',
            options={'ordering': ['name'], 'verbose_name': 'Réseau de boutiques', 'verbose_name_plural': 'Réseaux de boutiques'},
        ),
        migrations.AlterModelOptions(
            name='storeownership',
            options={'ordering': ['store__name', 'owner__user__username'], 'verbose_name': 'Propriété boutique', 'verbose_name_plural': 'Propriétés boutiques'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['store__name', 'product__name'], 'verbose_name': 'Produit en boutique', 'verbose_name_plural': 'Produits en boutiques'},
        ),
        migrations.AlterModelOptions(
            name='storeproductvariant',
            options={'ordering': ['store_product__store__name', 'variant__name'], 'verbose_name': 'Prix variante boutique', 'verbose_name_plural': 'Prix variantes boutiques'},
        ),
        migrations.AlterModelOptions(
            name='storeshareholder',
            options={'ordering': ['store__name', 'shareholder__user__username'], 'verbose_name': 'Part actionnaire', 'verbose_name_plural': 'Parts actionnaires'},
        ),
        migrations.AlterModelOptions(
            name='storetype',
            options={'ordering': ['name'], 'verbose_name': 'Type de boutique', 'verbose_name_plural': 'Types de boutiques'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-date_supply'], 'verbose_name': 'Approvisionnement', 'verbose_name_plural': 'Approvisionnements'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-id'], 'verbose_name': 'Ticket de support', 'verbose_name_plural': 'Tickets de support'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['name'], 'verbose_name': 'Taux de taxe', 'verbose_name_plural': 'Taux de taxes'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_transaction'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='typecard',
            options={'ordering': ['name'], 'verbose_name': 'Type de carte', 'verbose_name_plural': 'Types de cartes'},
        ),
        migrations.AlterModelOptions(
            name='unite',
            options={'ordering': ['-date'], 'verbose_name': 'Unité', 'verbose_name_plural': 'Unités'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name'], 'verbose_name': "Type d'utilisateur", 'verbose_name_plural': "Types d'utilisateurs"},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Entrepôt', 'verbose_name_plural': 'Entrepôts'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code de retrait', 'verbose_name_plural': 'Codes de retrait'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
