# Generated by Django 5.2.7 on 2026-03-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='api_boutiqu_store_1d1935_idx',
            old_name='api_boutiqu_store_i_83222a_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='api_boutiqu_store_836220_idx',
            old_name='api_boutiqu_store_i_f42173_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='api_boutiqu_product_45a7d7_idx',
            old_name='api_boutiqu_product_ac6878_idx',
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api_boutique_core.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(db_column='store', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api_boutique_core.store', verbose_name='Boutique'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_boutique_core.warehouse'),
        ),
    ]
