# Generated by Django 5.2.7 on 2026-03-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['store_product'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='api_boutiqu_store_i_83222a_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='api_boutiqu_store_i_f42173_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='api_boutiqu_product_ac6878_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='stock_qty_avail_idx',
            old_name='api_boutiqu_quantit_9ce49a_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='stock_status_idx',
            old_name='api_boutiqu_stock_s_571fc9_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='stock_last_restock_idx',
            old_name='api_boutiqu_last_re_433d23_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='api_boutique_core.stock'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store',
        ),
    ]
