# Generated by Django 5.2.7 on 2025-11-18 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0002_alter_accountingperiod_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productbrand',
            name='api_boutiqu_name_d2a612_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='average_basket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Panier moyen'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name="Nombre d'achats"),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_fully_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture'), ('over_stock', 'Surstock')], db_index=True, default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(db_index=True, default='Sénégal', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Numéro de lot'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(db_index=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='batch',
            name='manufacturing_date',
            field=models.DateField(db_index=True, verbose_name='Date de fabrication'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('social', 'Réseaux sociaux'), ('in_store', 'En magasin')], db_index=True, max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom campagne'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='card',
            name='num_card',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Numéro de carte'),
        ),
        migrations.AlterField(
            model_name='card',
            name='solde',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='Solde'),
        ),
        migrations.AlterField(
            model_name='card',
            name='statut',
            field=models.CharField(db_index=True, default='actif', max_length=150, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='date_transaction',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='type_transaction',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('achat', 'Achat'), ('retrait', 'Retrait'), ('credit', 'Crédit')], db_index=True, max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cashregistersession',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('suspended', 'Suspendue')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('open', 'Ouverture'), ('sale', 'Vente'), ('return', 'Retour'), ('payment', 'Paiement'), ('withdrawal', 'Retrait'), ('deposit', 'Dépôt'), ('close', 'Fermeture')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_purchase',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Premier achat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_purchase',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Dernier achat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Points fidélité'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='Total dépensé'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Par défaut'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom dashboard'),
        ),
        migrations.AlterField(
            model_name='databackup',
            name='backup_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date sauvegarde'),
        ),
        migrations.AlterField(
            model_name='databackup',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Complète'), ('incremental', 'Incrémentielle'), ('differential', 'Différentielle')], db_index=True, max_length=50, verbose_name='Type sauvegarde'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Heure livraison réelle'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_time',
            field=models.DateTimeField(db_index=True, verbose_name='Heure estimée'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('on_way', 'En chemin'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Adresse principale'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom itinéraire'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Arrivée effective'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='actual_departure',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Départ effectif'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True, verbose_name='Heure planifiée'),
        ),
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name="Plaque d'immatriculation"),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom du rayon'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(db_index=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, verbose_name='Date dépense'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom catégorie'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_type',
            field=models.CharField(choices=[('profit_loss', 'Compte de résultat'), ('balance_sheet', 'Bilan'), ('cash_flow', 'Flux de trésorerie'), ('sales', 'Ventes'), ('inventory', 'Stock')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='account_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='entry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='count_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date inventaire'),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='status',
            field=models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='planned', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='inventorycountitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventorycountitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom KPI'),
        ),
        migrations.AlterField(
            model_name='kpimeasurement',
            name='period_end',
            field=models.DateTimeField(db_index=True, verbose_name='Fin période'),
        ),
        migrations.AlterField(
            model_name='kpimeasurement',
            name='period_start',
            field=models.DateTimeField(db_index=True, verbose_name='Début période'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom programme'),
        ),
        migrations.AlterField(
            model_name='loyaltyreward',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom récompense'),
        ),
        migrations.AlterField(
            model_name='loyaltyreward',
            name='points_required',
            field=models.IntegerField(db_index=True, verbose_name='Points requis'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='completed_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date réalisation'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='equipment',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Équipement'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='scheduled_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date planifiée'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='status',
            field=models.CharField(db_index=True, default='scheduled', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='task_type',
            field=models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('predictive', 'Prédictive')], db_index=True, max_length=100, verbose_name='Type tâche'),
        ),
        migrations.AlterField(
            model_name='mobilemoney',
            name='action',
            field=models.CharField(db_index=True, max_length=45, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='mobilemoney',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mobilemoney',
            name='number',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='approval_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='return_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='return_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='status',
            field=models.CharField(choices=[('requested', 'Demandé'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('received', 'Reçu'), ('inspected', 'Inspecté'), ('refunded', 'Remboursé'), ('exchanged', 'Échangé'), ('completed', 'Terminé')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Code barre'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom variante'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selection',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sélectionnée'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(db_index=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(db_index=True, verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='retailsupply',
            name='name_product',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom produit'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de retour'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='variant_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Code variante'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='condition',
            field=models.CharField(choices=[('new', 'Neuf'), ('opened', 'Ouvert'), ('damaged', 'Endommagé'), ('defective', 'Défectueux')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='returnreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnreason',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='returnreason',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date vente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ticket_number',
            field=models.CharField(max_length=50, verbose_name='Numéro ticket'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date paiement'),
        ),
        migrations.AlterField(
            model_name='salestatus',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='securityincident',
            name='incident_type',
            field=models.CharField(choices=[('theft', 'Vol'), ('fraud', 'Fraude'), ('system_breach', 'Brèche système'), ('physical_breach', 'Brèche physique')], db_index=True, max_length=100, verbose_name='Type incident'),
        ),
        migrations.AlterField(
            model_name='securityincident',
            name='resolution_status',
            field=models.CharField(db_index=True, default='open', max_length=20, verbose_name='Statut résolution'),
        ),
        migrations.AlterField(
            model_name='securityincident',
            name='severity',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], db_index=True, max_length=20, verbose_name='Gravité'),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(db_index=True, verbose_name='Connexion'),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Déconnexion'),
        ),
        migrations.AlterField(
            model_name='sousservice',
            name='end_service',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fin du service'),
        ),
        migrations.AlterField(
            model_name='sousservice',
            name='nom_du_service',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom du service'),
        ),
        migrations.AlterField(
            model_name='sousservice',
            name='start_service',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Début du service'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_restocked',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Dernier réappro'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_available',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Quantité disponible'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound', 'Entrée'), ('outbound', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('return', 'Retour'), ('loss', 'Perte')], db_index=True, max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom boutique'),
        ),
        migrations.AlterField(
            model_name='storenetwork',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom du réseau'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif dans la boutique'),
        ),
        migrations.AlterField(
            model_name='storeproductvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storeproductvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='storeshareholder',
            name='investment_date',
            field=models.DateField(db_index=True, verbose_name="Date d'investissement"),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='date_supply',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='ref_supply',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('received', 'Reçu'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgent')], db_index=True, max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(db_index=True, default='open', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nom taxe'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('vente', 'Vente'), ('depot', 'Dépôt'), ('retrait', 'Retrait'), ('remboursement', 'Remboursement'), ('frais', 'Frais')], db_index=True, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='typecard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='typecard',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom du type'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom entrepôt'),
        ),
        migrations.AlterField(
            model_name='withdrawalcode',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='withdrawalcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='withdrawalcode',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='Expiré le'),
        ),
        migrations.AlterField(
            model_name='withdrawalcode',
            name='status',
            field=models.CharField(choices=[('unused', 'Inutilisé'), ('used', 'Utilisé'), ('expired', 'Expiré')], db_index=True, default='unused', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['start_date'], name='api_boutiqu_start_d_1bce2a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['is_closed'], name='api_boutiqu_is_clos_13ebe2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='api_boutiqu_action_320425_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name'], name='api_boutiqu_model_n_e2cf89_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='api_boutiqu_city_eaa7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='api_boutiqu_postal__5f6c15_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='api_boutiqu_country_b54917_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='api_boutiqu_expiry__8dd2df_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='api_boutiqu_batch_n_457922_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['manufacturing_date'], name='api_boutiqu_manufac_f425d9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='api_boutiqu_start_d_f7707d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='api_boutiqu_campaig_46c78b_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['client'], name='api_boutiqu_client__e533ae_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['solde'], name='api_boutiqu_solde_c72c67_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['statut'], name='api_boutiqu_statut_53e890_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['date_transaction'], name='api_boutiqu_date_tr_d32eef_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['type_transaction'], name='api_boutiqu_type_tr_40c46a_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card', 'date_transaction'], name='api_boutiqu_card_id_9c9b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['store'], name='api_boutiqu_store_i_8db75a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_976628_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['loyalty_points'], name='api_boutiqu_loyalty_7db182_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['total_spent'], name='api_boutiqu_total_s_7584b4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_purchase'], name='api_boutiqu_last_pu_41fbde_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['user'], name='api_boutiqu_user_id_38db62_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_default'], name='api_boutiqu_is_defa_c7b650_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['backup_date'], name='api_boutiqu_backup__93248e_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['backup_type'], name='api_boutiqu_backup__55405f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'estimated_time'], name='api_boutiqu_status_d08f13_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['assigned_driver', 'status'], name='api_boutiqu_assigne_a93554_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['estimated_time'], name='api_boutiqu_estimat_8bca66_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status_changed_at'], name='api_boutiqu_status__f33677_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['customer'], name='api_boutiqu_custome_cab901_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['is_primary'], name='api_boutiqu_is_prim_c8d28f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['store'], name='api_boutiqu_store_i_e57d68_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['driver'], name='api_boutiqu_driver__913697_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['delivery'], name='api_boutiqu_deliver_6f4725_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedule',
            index=models.Index(fields=['scheduled_time'], name='api_boutiqu_schedul_320e27_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryvehicle',
            index=models.Index(fields=['store'], name='api_boutiqu_store_i_a54c82_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryvehicle',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_4ae31a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['store'], name='api_boutiqu_store_i_6fed32_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='api_boutiqu_name_4f3341_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['store', 'name'], name='api_boutiqu_store_i_5f80dc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_81a9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['store', 'is_active'], name='api_boutiqu_store_i_689afa_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role', 'is_active'], name='api_boutiqu_role_id_143e76_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='api_boutiqu_hire_da_775ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['resolved'], name='api_boutiqu_resolve_1d3683_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='api_boutiqu_expense_ff9bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['store', 'expense_date'], name='api_boutiqu_store_i_b65ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialreport',
            index=models.Index(fields=['generated_at'], name='api_boutiqu_generat_ada20c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialreport',
            index=models.Index(fields=['report_type'], name='api_boutiqu_report__fb8cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['reference'], name='api_boutiqu_referen_2fbf89_idx'),
        ),
        migrations.AddIndex(
            model_name='kpimeasurement',
            index=models.Index(fields=['period_start'], name='api_boutiqu_period__ea6b31_idx'),
        ),
        migrations.AddIndex(
            model_name='kpimeasurement',
            index=models.Index(fields=['kpi', 'period_start'], name='api_boutiqu_kpi_id_7285ab_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyprogram',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_8e4226_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyprogram',
            index=models.Index(fields=['store', 'is_active'], name='api_boutiqu_store_i_fd7944_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['scheduled_date'], name='api_boutiqu_schedul_dc6f67_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['status'], name='api_boutiqu_status_d5eb65_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['equipment'], name='api_boutiqu_equipme_f5ab36_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoney',
            index=models.Index(fields=['date'], name='api_boutiqu_date_6506e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoney',
            index=models.Index(fields=['action'], name='api_boutiqu_action_ddf61a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'status'], name='api_boutiqu_is_acti_3eec49_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_price'], name='api_boutiqu_base_pr_d17294_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='api_boutiqu_created_238f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='api_boutiqu_name_b20278_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['sort_order'], name='api_boutiqu_sort_or_b7826f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['status'], name='api_boutiqu_status_59d2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['store', 'return_date'], name='api_boutiqu_store_i_9e1e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['name'], name='api_boutiqu_name_6028db_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['prix_vente'], name='api_boutiqu_prix_ve_2fa6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date'], name='api_boutiqu_start_d_7b8811_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['end_date'], name='api_boutiqu_end_dat_55a12f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['store', 'start_date'], name='api_boutiqu_store_i_d2e8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_date'], name='api_boutiqu_refund__8495d9_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_method'], name='api_boutiqu_refund__8d4a67_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderrule',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_eef753_idx'),
        ),
        migrations.AddIndex(
            model_name='retailsupply',
            index=models.Index(fields=['name_product'], name='api_boutiqu_name_pr_005fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='returnedproduct',
            index=models.Index(fields=['return_date'], name='api_boutiqu_return__247cac_idx'),
        ),
        migrations.AddIndex(
            model_name='returnedproduct',
            index=models.Index(fields=['employee'], name='api_boutiqu_employe_0fb962_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['product_return'], name='api_boutiqu_product_a162ca_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['condition'], name='api_boutiqu_conditi_1eb19d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'ticket_number'], name='api_boutiqu_store_i_ca6d05_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'status', 'sale_date'], name='api_boutiqu_store_i_dcd884_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_fully_paid'], name='api_boutiqu_is_full_5a840f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['total_amount'], name='api_boutiqu_total_a_d7fb50_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='api_boutiqu_sale_id_be8455_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='api_boutiqu_product_6d3813_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['payment_date'], name='api_boutiqu_payment_8f8a52_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale', 'payment_method'], name='api_boutiqu_sale_id_8ef7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['incident_type'], name='api_boutiqu_inciden_04f7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['severity'], name='api_boutiqu_severit_c32559_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['resolution_status'], name='api_boutiqu_resolut_03008f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['login_time'], name='api_boutiqu_login_t_c8a5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['logout_time'], name='api_boutiqu_logout__d3313b_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'login_time'], name='api_boutiqu_user_id_4623be_idx'),
        ),
        migrations.AddIndex(
            model_name='sousservice',
            index=models.Index(fields=['start_service'], name='api_boutiqu_start_s_bf8d58_idx'),
        ),
        migrations.AddIndex(
            model_name='sousservice',
            index=models.Index(fields=['end_service'], name='api_boutiqu_end_ser_90a559_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['store', 'quantity_available'], name='api_boutiqu_store_i_f42173_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stock_status'], name='api_boutiqu_stock_s_571fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_restocked'], name='api_boutiqu_last_re_433d23_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'store', 'quantity_available'], name='api_boutiqu_product_ac6878_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='api_boutiqu_name_ae3a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_8f6238_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='api_boutiqu_created_5c83d2_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_type', 'is_active'], name='api_boutiqu_store_t_476644_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='api_boutiqu_name_9f208a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['store', 'name'], name='api_boutiqu_store_i_001419_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['date_supply'], name='api_boutiqu_date_su_1f7736_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['status'], name='api_boutiqu_status_a90cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['supplier'], name='api_boutiqu_supplie_658025_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['store', 'date_supply'], name='api_boutiqu_store_i_f4b5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='api_boutiqu_priorit_89d354_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='api_boutiqu_status_dec757_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date_transaction'], name='api_boutiqu_date_tr_b2481b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type_transaction'], name='api_boutiqu_type_tr_756c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date_transaction'], name='api_boutiqu_user_id_6cad18_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='api_boutiqu_usernam_0ed6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='api_boutiqu_email_58402d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='api_boutiqu_phone_950749_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='api_boutiqu_date_jo_803a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_19231c_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['store', 'is_active'], name='api_boutiqu_store_i_fae1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalcode',
            index=models.Index(fields=['status'], name='api_boutiqu_status_4d1abb_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalcode',
            index=models.Index(fields=['expires_at'], name='api_boutiqu_expires_f9814a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('store', 'ticket_number'), name='unique_ticket_per_store'),
        ),
    ]
