# Generated by Django 5.2.7 on 2026-01-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
