# Generated by Django 5.2.7 on 2026-02-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0003_remove_user_user_type_delete_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetype',
            name='code',
        ),
        migrations.CreateModel(
            name='StoreDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Appareil')),
                ('device_name', models.CharField(max_length=100, verbose_name="Nom de l'appareil")),
                ('device_type', models.CharField(choices=[('CAISSE', 'Caisse enregistreuse'), ('TABLETTE', 'Tablette'), ('MOBILE', 'Mobile personnel'), ('KIOSK', 'Kiosk client'), ('AUTRE', 'Autre appareil')], default='TABLETTE', max_length=20, verbose_name='Type')),
                ('pairing_code', models.CharField(blank=True, db_index=True, max_length=25, unique=True, verbose_name="Code d'appairage")),
                ('qr_code_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Token QR Code')),
                ('pairing_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code')),
                ('paired_at', models.DateTimeField(blank=True, null=True, verbose_name='Appairé le')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('current_session', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session actuelle')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='Version OS')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='Version App')),
                ('permissions', models.JSONField(default=dict, verbose_name='Permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api_boutique_core.store')),
            ],
            options={
                'verbose_name': 'Appareil boutique',
                'verbose_name_plural': 'Appareils boutique',
                'ordering': ['store__name', '-last_login'],
            },
        ),
        migrations.CreateModel(
            name='StoreQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du QR Code')),
                ('qr_type', models.CharField(choices=[('PAIEMENT', 'QR Code de paiement'), ('CONNEXION', 'QR Code de connexion'), ('PROMOTION', 'QR Code promotionnel'), ('MENU', 'QR Code menu digital'), ('LIVRAISON', 'QR Code livraison')], default='PAIEMENT', max_length=20, verbose_name='Type')),
                ('qr_data', models.TextField(verbose_name='Données QR')),
                ('qr_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token QR')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant fixe')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de scans')),
                ('last_scan', models.DateTimeField(blank=True, null=True, verbose_name='Dernier scan')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Valide du')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Valide jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api_boutique_core.store')),
            ],
            options={
                'verbose_name': 'QR Code boutique',
                'verbose_name_plural': 'QR Codes boutique',
                'ordering': ['store__name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token session')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Session active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api_boutique_core.storedevice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api_boutique_core.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session boutique',
                'verbose_name_plural': 'Sessions boutique',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['store', 'is_active'], name='api_boutiqu_store_i_1ae536_idx'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['pairing_code'], name='api_boutiqu_pairing_9c555e_idx'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['qr_code_token'], name='api_boutiqu_qr_code_b164f1_idx'),
        ),
        migrations.AddIndex(
            model_name='storedevice',
            index=models.Index(fields=['pairing_expires_at'], name='api_boutiqu_pairing_6ce9da_idx'),
        ),
        migrations.AddIndex(
            model_name='storeqrcode',
            index=models.Index(fields=['store', 'qr_type', 'is_active'], name='api_boutiqu_store_i_cbaba6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeqrcode',
            index=models.Index(fields=['qr_token'], name='api_boutiqu_qr_toke_1e4210_idx'),
        ),
        migrations.AddIndex(
            model_name='storeqrcode',
            index=models.Index(fields=['valid_until', 'is_active'], name='api_boutiqu_valid_u_2c4252_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['store', 'is_active'], name='api_boutiqu_store_i_f7353b_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['device', 'is_active'], name='api_boutiqu_device__770090_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['expires_at', 'is_active'], name='api_boutiqu_expires_6b3544_idx'),
        ),
    ]
