# Generated by Django 5.2.7 on 2025-12-02 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0003_remove_productbrand_api_boutiqu_name_d2a612_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Source de commande',
                'verbose_name_plural': 'Sources de commande',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#3498db', max_length=20, verbose_name='Couleur')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Statut de commande',
                'verbose_name_plural': 'Statuts de commande',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro commande')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Référence externe')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais livraison')),
                ('total_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Total')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Nom client')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email client')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone client')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse livraison')),
                ('shipping_notes', models.TextField(blank=True, verbose_name='Notes livraison')),
                ('expected_delivery_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Date livraison prévue')),
                ('actual_delivery_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date livraison effective')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiel'), ('paid', 'Payé'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20, verbose_name='Statut paiement')),
                ('converted_to_sale', models.BooleanField(db_index=True, default=False, verbose_name='Converti en vente')),
                ('conversion_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date conversion')),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date commande')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('estimated_preparation_time', models.IntegerField(default=30, verbose_name='Temps préparation estimé (min)')),
                ('preparation_start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Début préparation')),
                ('preparation_end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fin préparation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api_boutique_core.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_orders', to='api_boutique_core.employee')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_boutique_core.paymentmethod')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_order', to='api_boutique_core.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api_boutique_core.store')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api_boutique_core.ordersource')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api_boutique_core.orderstatus')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('discount_rate', models.FloatField(default=0, verbose_name='Taux remise')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remise')),
                ('tax_rate', models.FloatField(default=0, verbose_name='Taux taxe')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant taxe')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total ligne')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_boutique_core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api_boutique_core.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_boutique_core.productvariant')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'ordering': ['order', 'product__name'],
                'indexes': [models.Index(fields=['order', 'product'], name='api_boutiqu_order_i_bfc792_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='api_boutiqu_order_d_0c0f13_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', 'order_date'], name='api_boutiqu_store_i_db2975_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'order_date'], name='api_boutiqu_custome_98b73e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='api_boutiqu_status__4bebf9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='api_boutiqu_expecte_38cd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['converted_to_sale'], name='api_boutiqu_convert_02f2fc_idx'),
        ),
    ]
