# Generated by Django 5.2.7 on 2025-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0004_ordersource_orderstatus_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sub_category',
            field=models.CharField(db_index=True, default=1, max_length=150, verbose_name='Sub_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nom'),
        ),
    ]
