# Generated by Django 5.2.7 on 2026-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0004_remove_storetype_code_storedevice_storeqrcode_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='store',
            name='api_boutiqu_created_5c83d2_idx',
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at', 'updated_at'], name='api_boutiqu_created_098000_idx'),
        ),
    ]
