# Generated by Django 5.2.7 on 2026-01-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0005_productcategory_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='api_boutiqu_categor_2907cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_boutiqu_is_acti_3eec49_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='api_boutiqu_product_2b441e_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jour_ecart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qt_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='prix_reduction',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat spécifique à cette variante", max_digits=12, null=True, verbose_name="Prix d'achat variante"),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='jour_ecart',
            field=models.IntegerField(default=15, verbose_name='Jours écart'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='qt_item',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité par item'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api_boutique_core.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='storeproductvariant',
            name='prix_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix réduit'),
        ),
        migrations.AddField(
            model_name='storeproductvariant',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='storeproductvariant',
            name='selection',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sélectionnée'),
        ),
        migrations.AddField(
            model_name='storeproductvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente au client', max_digits=12, null=True, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix barré pour les promotions', max_digits=12, null=True, verbose_name='Prix comparé'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat au fournisseur", max_digits=12, null=True, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente spécifique à cette variante', max_digits=12, null=True, verbose_name='Prix de vente variante'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='api_boutiqu_categor_ee21ca_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='api_boutiqu_is_acti_1a904e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['cost_price'], name='api_boutiqu_cost_pr_fc81cf_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='api_boutiqu_product_228719_idx'),
        ),
    ]
