# Generated by Django 5.2.7 on 2026-03-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0002_fix_stock_fields'),
        ('api_boutique_core', '0002_rename_api_boutiqu_store_i_83222a_idx_api_boutiqu_store_1d1935_idx_and_more'),
        ('api_boutique_core', '0005_productcategory_sub_category_and_more'),
    ]

    operations = [
    ]
