# Generated by Django 5.2.7 on 2026-02-09 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0005_remove_store_api_boutiqu_created_5c83d2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('manager', 'Gérant'), ('cashier', 'Caissier'), ('stock_manager', 'Responsable stock'), ('viewer', 'Consultant')], default='viewer', max_length=20)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_sales', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_permissions', to='api_boutique_core.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_boutique_core.store')),
            ],
            options={
                'verbose_name': 'Permission boutique',
                'verbose_name_plural': 'Permissions boutiques',
                'unique_together': {('employee', 'store')},
            },
        ),
    ]
