# Generated by Django 5.2.7 on 2026-01-07 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0006_remove_product_api_boutiqu_categor_2907cb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='count_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date inventaire'),
        ),
    ]
