# Generated by Django 5.2.7 on 2026-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0007_alter_inventorycount_count_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminé à'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date planifiée'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Débuté à'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['planned_date'], name='api_boutiqu_planned_52dbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['completed_at'], name='api_boutiqu_complet_edd846_idx'),
        ),
    ]
