# Generated by Django 5.2.7 on 2026-01-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0008_inventorycount_completed_at_inventorycount_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='api_boutique_core.store'),
        ),
    ]
