# Generated by Django 5.2.7 on 2026-02-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0008_pack_packitem_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='sub_category',
        ),
    ]
