# Generated by Django 5.2.7 on 2026-02-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0009_alter_supplier_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.RemoveIndex(
            model_name='inventorycount',
            name='api_boutiqu_planned_52dbc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorycount',
            name='api_boutiqu_complet_edd846_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_boutiqu_base_pr_d17294_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_boutiqu_cost_pr_fc81cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='api_boutiqu_prix_ve_2fa6a5_idx',
        ),
        migrations.RemoveField(
            model_name='inventorycount',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='inventorycount',
            name='planned_date',
        ),
        migrations.RemoveField(
            model_name='inventorycount',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='prix_vente',
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='count_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date inventaire'),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api_boutique_core.supplier', verbose_name='Fournisseur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeproductvariant',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='api_boutique_core.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email_address'),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
