# Generated by Django 5.2.7 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0009_remove_productcategory_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nom'),
        ),
    ]
