# Generated by Django 5.2.7 on 2026-02-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0010_alter_productcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='updated_by',
        ),
    ]
