# Generated by Django 5.2.7 on 2026-02-18 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0011_remove_productbrand_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
