# Generated by Django 5.2.7 on 2026-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0012_productbrand_created_at_productbrand_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
    ]
