# Generated by Django 5.2.7 on 2026-02-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0014_remove_product_created_by_remove_product_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
