# Generated by Django 5.2.7 on 2026-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0015_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nombre_item',
            field=models.IntegerField(default=0, verbose_name='nombre_item'),
        ),
    ]
