# Generated by Django 5.2.7 on 2026-03-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0016_product_nombre_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nombre_item',
            field=models.IntegerField(default=1, verbose_name='nombre_item'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='qt_item',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité item'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api_boutique_core.supplier', verbose_name='Fournisseur'),
        ),
    ]
