# Generated by Django 5.2.7 on 2026-03-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_boutique_core', '0017_alter_product_nombre_item_alter_storeproduct_qt_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_group', to='api_boutique_core.productcategory', verbose_name='Group'),
        ),
    ]
