"""
Django settings for backend_boutique project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import datetime
from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url

# Charger les variables d'environnement depuis un fichier .env
load_dotenv()

# ——————————————————————
# Chemin de base du projet
# ——————————————————————
BASE_DIR = Path(__file__).resolve().parent.parent

# ——————————————————————
# Sécurité / Debug
# ——————————————————————
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-++dh&j@7d58xsi!g#lv54&x!mzt+k-7u04&cseanf&5*alg+wc')

DEBUG = os.environ.get('DJANGO_DEBUG', 'True')

ALLOWED_HOSTS = ['*']  # Temporaire pour développement

# ——————————————————————
# Applications installées
# ——————————————————————
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps tierces
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'corsheaders',
    'django_filters',

    # Application principale
    'api_boutique_core',
]

# ——————————————————————
# Middleware - OPTIMISÉ AVEC CACHE
# ——————————————————————
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',  # Cache - DOIT ÊTRE EN PREMIER
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',  # Cache - DOIT ÊTRE EN DERNIER
]
# Optionnel : compression et mise en cache
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ROOT_URLCONF = 'backend_boutique.urls'

# ——————————————————————
# Templates
# ——————————————————————
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_boutique.wsgi.application'

# ——————————————————————
# Base de données — PostgreSQL avec correction pour Supabase
# ——————————————————————
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # 🔥 CORRECTION CRITIQUE : Utiliser le port 6543 pour Supabase (transaction pooler)
    if 'supabase.com' in DATABASE_URL:
        DATABASE_URL = DATABASE_URL.replace(':5432', ':6543')
        print(f"✅ URL base de données corrigée pour Supabase (port 6543)")
    
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0,  # 🔥 CORRECTION : 0 au lieu de 600 pour éviter l'épuisement du pool
            conn_health_checks=True
        )
    }
    
    # 🔥 AJOUT : Forcer SSL pour Supabase
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
    }
    
    print(f"✅ Configuration DB: conn_max_age=0, SSL requis")
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'boutik_db',
            'USER': os.environ.get("DB_USER"),
            'PASSWORD': os.environ.get("DB_PASSWORD"),
            'HOST': 'localhost',
            'PORT': os.environ.get("DB_PORT"),
        }
    }
# ——————————————————————
# Configuration du Cache - NOUVEAU
# ——————————————————————
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60,  # 1 minute
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Configuration cache middleware
CACHE_MIDDLEWARE_SECONDS = 30  # Cache les pages 30 secondes
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_KEY_PREFIX = 'boutique'

# Cache pour les sessions utilisateur
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# ——————————————————————
# Modèle utilisateur personnalisé
# ——————————————————————
AUTH_USER_MODEL = 'api_boutique_core.User'

# ——————————————————————
# Validation des mots de passe
# ——————————————————————
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ——————————————————————
# Internationalisation
# ——————————————————————
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Abidjan'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ——————————————————————
# Fichiers statiques & médias
# ——————————————————————
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ——————————————————————
# Clé par défaut des PK
# ——————————————————————
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ——————————————————————
# Configuration REST Framework - OPTIMISÉE
# ——————————————————————
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',  # Évite COUNT(*)
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# ——————————————————————
# Configuration JWT
# ——————————————————————
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ——————————————————————
# CORS Configuration
# ——————————————————————
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://0.0.0.0:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT',
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# ——————————————————————
# Configuration Swagger
# ——————————————————————
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'DOC_EXPANSION': 'none',
    'SHOW_REQUEST_HEADERS': True,
}

# ——————————————————————
# Configuration des logs - OPTIMISÉE
# ——————————————————————
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',  # Seulement les erreurs dans le fichier
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, f'debug_{datetime.datetime.now().strftime("%Y%m%d")}.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',  # Réduit le bruit en console
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api_boutique_core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'level': 'WARNING',  # Réduit les logs SQL
            'handlers': ['console'],
            'propagate': False,
        },
    },
}

# ——————————————————————
# Configuration email
# ——————————————————————
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# ——————————————————————
# Configuration des sessions
# ——————————————————————
SESSION_COOKIE_AGE = 1209600  # 2 semaines
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ——————————————————————
# Configuration CSRF
# ——————————————————————
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SECURE = False

# ——————————————————————
# Autres paramètres
# ——————————————————————
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# ——————————————————————
# Variables personnalisées
# ——————————————————————
BOUTIQUE_CONFIG = {
    'APP_NAME': 'Boutik Management System',
    'VERSION': '2.0.0',
    'SUPPORT_EMAIL': 'support@boutik.com',
    'MAX_PRODUCT_IMAGES': 5,
    'DEFAULT_CURRENCY': 'XOF',
    'LOYALTY_POINTS_RATE': 0.01,
    'DEFAULT_STORE_ID': 1,
}

# ——————————————————————
# Configuration pour le développement
# ——————————————————————
if DEBUG:
    SILENCED_SYSTEM_CHECKS = [
        'security.W001', 'security.W002', 'security.W003', 'security.W004',
        'security.W008', 'security.W009', 'security.W012', 'security.W016',
    ]

# ——————————————————————
# Configuration de sécurité pour la production
# ——————————————————————
if not DEBUG:
    # Sécurité en production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    ALLOWED_HOSTS = ['votre-domaine.com', 'www.votre-domaine.com']
    
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://votre-frontend.com",
        "https://www.votre-frontend.com",
    ]
    
    CSRF_TRUSTED_ORIGINS = [
        "https://votre-domaine.com",
        "https://www.votre-domaine.com",
    ]
